TARGET	=	test
FC	=	/usr/local/Packages/mvapich2-tcp-intel-1.2rc2/bin/mpif90
FOPT	=	-O3
LIB	=	-L/usr/local/Packages/mvapich2-tcp-intel-1.2rc2/lib

all:
	$(FC) slave.f90 $(FOPT) -c -o slave.o
#	$(FC) master.f90 $(FOPT) -c -o master.o
	$(FC) main.f90 $(FOPT) -c -o main.o
	$(FC) slave.o main.o \
		$(FOPT) $(LIB) -o $(TARGET)

run:
	qsub run.sh -q opt.q

clean:
	rm -f *~
	rm -f *.o
	rm -f $(TARGET)
	rm -f MPI_test*

