        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb  7 17:22:23 2012
        MODULE PULSE_ALPHA_Z_SIN2__genmod
          INTERFACE 
            FUNCTION PULSE_ALPHA_Z_SIN2(T) RESULT(F)
              COMPLEX(KIND=8), INTENT(IN) :: T
              COMPLEX(KIND=8) :: F
            END FUNCTION PULSE_ALPHA_Z_SIN2
          END INTERFACE 
        END MODULE PULSE_ALPHA_Z_SIN2__genmod
