        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb  7 17:21:03 2012
        MODULE PULSE_ALPHA2_X_CONST__genmod
          INTERFACE 
            FUNCTION PULSE_ALPHA2_X_CONST(T) RESULT(F)
              COMPLEX(KIND=8), INTENT(IN) :: T
              COMPLEX(KIND=8) :: F
            END FUNCTION PULSE_ALPHA2_X_CONST
          END INTERFACE 
        END MODULE PULSE_ALPHA2_X_CONST__genmod
