        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb  7 17:21:03 2012
        MODULE PULSE_ALPHA_Z_CONST__genmod
          INTERFACE 
            FUNCTION PULSE_ALPHA_Z_CONST(T_) RESULT(ALPHA_Z)
              COMPLEX(KIND=8), INTENT(IN) :: T_
              COMPLEX(KIND=8) :: ALPHA_Z
            END FUNCTION PULSE_ALPHA_Z_CONST
          END INTERFACE 
        END MODULE PULSE_ALPHA_Z_CONST__genmod
