        !COMPILER-GENERATED INTERFACE MODULE: Tue Feb  7 17:21:03 2012
        MODULE PULSE_ALPHA_X_CONST__genmod
          INTERFACE 
            FUNCTION PULSE_ALPHA_X_CONST(T_) RESULT(ALPHA_X)
              COMPLEX(KIND=8), INTENT(IN) :: T_
              COMPLEX(KIND=8) :: ALPHA_X
            END FUNCTION PULSE_ALPHA_X_CONST
          END INTERFACE 
        END MODULE PULSE_ALPHA_X_CONST__genmod
